name: Build Docker Image
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: |
          docker build -t weaviateui .
          docker save weaviateui -o weaviateui.tar
      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: weaviateui-docker
          path: weaviateui.tar